version: '3.0'
services:
  talkent-app:
    volumes:
        - ./:/app
        - /app/node_modules
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    command: npm run dev